import { labelWorkOrderType } from "@/lib/activity-labels";
import type { WorkOrderType } from "@/types";

const AUTO_WO_RX = /^\s*\[AUTO\]/i;
const AUTO_WO_ANY_RX = /\[AUTO\]|\bautomatski\b/i;

/** Da li je opis generisan sistemom (ne ručni unos kancelarije). */
export function isAutoGeneratedWorkOrderDescription(description: string | null | undefined): boolean {
  const t = (description ?? "").trim();
  if (!t) return false;
  return AUTO_WO_RX.test(t) || /\bautomatski je (kreiran|otvoren) radni nalog\b/i.test(t);
}

function defaultTaskForType(type?: WorkOrderType): string {
  switch (type) {
    case "measurement":
    case "measurement_verification":
      return "Merenje na objektu.";
    case "installation":
      return "Montaža na objektu.";
    case "production":
      return "Rad u proizvodnji.";
    case "complaint":
      return "Reklamacioni obilazak.";
    case "service":
      return "Servis na lokaciji.";
    case "site_visit":
      return "Terenska poseta.";
    default:
      return type ? `${labelWorkOrderType(type)} na objektu.` : "Obilazak lokacije.";
  }
}

/** Uklanja dispečerske fraze koje radnik ne treba da vidi na terenu. */
function stripDispatcherPhrases(text: string): string {
  return text
    .replace(/\s*zakažite\s+montažu[^.]*\.?/gi, "")
    .replace(/\s*čeka\s+dodelu\s+tima\.?/gi, "")
    .replace(/\s*čeka\s+rešavanje\s+pre\s+nastavka[^.]*\.?/gi, "")
    .replace(/\s*materijal\s+spreman\s+u\s+magacinu\.?/gi, "")
    .replace(/\s*automatski\s+je\s+(kreiran|otvoren)\s+radni\s+nalog[^.]*\.?/gi, "")
    .replace(/\s*evidentiran\s+problem\s+na\s+ugradnji[^.]*\.?/gi, "")
    .replace(/\s*otvoren\s+novi\s+nalog[^.]*\.?/gi, "")
    .replace(/\s*ponovno\s+zakazivanje\s+ugradnje\.?/gi, "")
    .replace(/\s*deo\s+obezbeđen\s*\([^)]*\)\.?\s*/gi, "")
    .replace(/\s{2,}/g, " ")
    .replace(/^[,;|–—-]+\s*/, "")
    .replace(/\s*[,;|–—-]+\s*$/, "")
    .trim();
}

function formatAutoDescription(raw: string, type?: WorkOrderType): string {
  let text = raw.replace(/^\s*\[AUTO\]\s*/i, "").trim();

  const pozMatch = text.match(/poz\.\s*([^.)]+)/i);
  if (/dopuna\s+ugradnje/i.test(text)) {
    if (pozMatch?.[1]?.trim()) {
      return `Ugraditi nedostajući deo sa predračuna (poz. ${pozMatch[1].trim()}).`;
    }
    return "Ugraditi nedostajući deo sa predračuna.";
  }

  if (/teren\s+otkazan/i.test(text)) {
    const reason = text.replace(/^.*?otkazan\.?\s*/i, "").trim();
    return reason.length > 2 ? `Otkazano na terenu: ${reason}` : "Ponovni obilazak — proverite sa kancelarijom.";
  }

  if (/problem\s+na\s+ugradnji/i.test(text)) {
    return "Montaža na lokaciji (nastavak posle prethodnog problema).";
  }

  if (/ponovn(a|o)\s+(kontrola\s+mera|merenje)/i.test(text)) {
    return "Merenje / provera mera na objektu.";
  }

  if (/dopun/i.test(text) && /stavk/i.test(text)) {
    const tail = text.match(/izveštaju:\s*(.+)$/i)?.[1]?.trim();
    return tail && tail.length > 2 ? tail : "Dopuna radova na lokaciji — pogledajte stavke na nalogu.";
  }

  if (/dopun/i.test(text) && /teren/i.test(text)) {
    return "Dopuna radova na lokaciji.";
  }

  if (/procena\s+ugradnje/i.test(text)) {
    const hours = text.match(/(\d+(?:[.,]\d+)?)\s*h/i)?.[1];
    return hours ? `Montaža na objektu (procena oko ${hours} h).` : "Montaža na objektu.";
  }

  if (/procena\s+trajanja\s+ugradnje/i.test(text)) {
    return "Montaža na objektu — procena sati još nije uneta u sistemu.";
  }

  text = stripDispatcherPhrases(text);
  if (!text || text.length < 6) {
    return defaultTaskForType(type);
  }

  return text.endsWith(".") ? text : `${text}.`;
}

/** Opis za prikaz radniku na terenu — bez [AUTO] i dispečerskih uputa. */
export function formatWorkOrderDescriptionForWorker(
  description: string | null | undefined,
  type?: WorkOrderType,
): string {
  const raw = (description ?? "").trim();
  if (!raw) return defaultTaskForType(type);

  if (isAutoGeneratedWorkOrderDescription(raw) || AUTO_WO_ANY_RX.test(raw)) {
    return formatAutoDescription(raw, type);
  }

  if (/^zakazan[ao]?\s+(merenje|ugradnja)/i.test(raw)) {
    const note = raw.match(/napomena:\s*(.+?)(?:\s*\||$)/i)?.[1]?.trim();
    if (note) return note;
    if (type === "installation") {
      return "Montaža po rasporedu — pogledajte stavke na nalogu ispod.";
    }
    return defaultTaskForType(type);
  }

  return raw;
}
