import { useEffect, useRef } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import { JobStatus, WorkOrder, type WorkOrderCreateInput } from "@/types";
import { useToast } from "@/hooks/use-toast";
import { useAuthStore } from "@/stores/auth-store";
import { isFieldExecutionRole } from "@/lib/field-team-access";
import { upsertSystemActivity } from "@/lib/activity-automation";
import { labelJobStatus, labelWorkOrderStatus, labelWorkOrderType } from "@/lib/activity-labels";
import { recomputeJobStatus } from "@/lib/job-status-automation";
import { ensureWorkflowWorkOrders } from "@/lib/work-order-workflow-automation";
import {
  DASHBOARD_ACCEPTED_MEASUREMENT_FROM_JOBS_QUERY_KEY,
  DASHBOARD_WORK_ORDERS_MISSING_TEAM_QUERY_KEY,
} from "@/hooks/use-unscheduled-work-orders-dashboard";
import { invalidateWorkOrderQueries, patchWorkOrderInAllCaches } from "@/lib/work-order-query-cache";
import { workOrderScheduledDatetimeForDb } from "@/lib/work-order-schedule-calendar";

const AUTO_WO_DESCRIPTION_RX = /^\s*\[AUTO\]|\bautomatski\b/i;

function isAutoGeneratedWorkOrder(prevRow: Record<string, unknown> | null | undefined): boolean {
  if (!prevRow) return false;
  if (prevRow.automation_field_report_id != null) return true;
  const description = typeof prevRow.description === "string" ? prevRow.description : "";
  return AUTO_WO_DESCRIPTION_RX.test(description);
}

async function resolvePreviousJobStatusFromActivities(jobId: string, currentStatus: string): Promise<JobStatus | null> {
  const { data, error } = await supabase
    .from("activities")
    .select("system_key, date")
    .eq("job_id", jobId)
    .like("system_key", "job-status:%")
    .order("date", { ascending: false })
    .limit(30);
  if (error) return null;
  const rows = Array.isArray(data) ? data : [];
  for (const row of rows) {
    const systemKey = typeof row.system_key === "string" ? row.system_key : "";
    const match = systemKey.match(/^job-status:[^:]+:([^:]+):([^:]+)$/);
    if (!match) continue;
    const [, previous, next] = match;
    if (next === currentStatus) return previous as JobStatus;
  }
  return null;
}

export function useWorkOrders(jobId?: string) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { user } = useAuthStore();
  const realtimeInstanceIdRef = useRef(
    `work-orders-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`,
  );

  const runStatusAutomation = async (targetJobId?: string) => {
    if (!targetJobId) return;
    try {
      await ensureWorkflowWorkOrders(targetJobId);
    } catch (err) {
      console.warn("ensureWorkflowWorkOrders posle promene RN:", err);
    }
    try {
      await recomputeJobStatus(targetJobId, user?.id ?? null);
    } catch (err) {
      console.warn("Auto status recompute failed after work order change:", err);
    }
  };

  const { data: workOrders, isLoading, isError, error } = useQuery({
    queryKey: ["work-orders", jobId, user?.id, user?.role],
    staleTime: 0,
    refetchOnMount: "always",
    queryFn: async () => {
      let query = supabase
        .from("work_orders")
        .select(`
          *,
          jobs (id, job_number, installation_address, installation_apartment, installation_floor, customers (name)),
          files (id, filename, storage_key, storage_url)
        `)
        .order("created_at", { ascending: false });

      if (jobId) {
        query = query.eq("job_id", jobId);
      }

      if (user && isFieldExecutionRole(user.role)) {
        if (user.teamId) {
          query = query.eq("team_id", user.teamId);
        } else {
          return [];
        }
      }

      const { data, error: queryError } = await query;

      if (queryError) throw queryError;

      const rows = Array.isArray(data) ? data : [];

      return rows.map((d) => {
        const fileEmbed = (d as { files?: { id?: string; filename?: string } | { id?: string; filename?: string }[] | null })
          .files;
        const fileRow = Array.isArray(fileEmbed) ? fileEmbed[0] : fileEmbed;
        const rawFid = (d as { file_id?: string | null }).file_id;
        const fileIdFromRow = typeof rawFid === "string" ? rawFid : undefined;
        const attachmentFileId = fileRow?.id ?? fileIdFromRow ?? undefined;
        const attachmentName =
          typeof fileRow?.filename === "string" && fileRow.filename.trim()
            ? fileRow.filename
            : attachmentFileId
              ? "Prilog"
              : undefined;
        return {
          id: d.id,
          jobId: d.job_id,
          type: d.type,
          description: d.description,
          measurementLocation: (d as { measurement_location?: string | null }).measurement_location ?? undefined,
          measurementScope: (d as { measurement_scope?: string | null }).measurement_scope ?? undefined,
          assignedTeamId: d.team_id,
          date: d.date,
          status: d.status,
          attachmentFileId,
          attachmentName,
          fieldStartedAt:
            typeof (d as { field_started_at?: string | null }).field_started_at === "string"
              ? (d as { field_started_at: string }).field_started_at
              : undefined,
          fieldCompletedAt:
            typeof (d as { field_completed_at?: string | null }).field_completed_at === "string"
              ? (d as { field_completed_at: string }).field_completed_at
              : undefined,
          installationRef: (d as { installation_ref?: string | null }).installation_ref ?? undefined,
          productionRef: (d as { production_ref?: string | null }).production_ref ?? undefined,
          createdAt: (d as { created_at?: string }).created_at,
          job: d.jobs
            ? (() => {
                const jobRow = d.jobs as {
                  id: string;
                  job_number: string;
                  installation_address?: string | null;
                  installation_apartment?: string | null;
                  installation_floor?: string | null;
                  customers?: { name?: string } | { name?: string }[] | null;
                };
                const custRaw = jobRow.customers;
                const cust = Array.isArray(custRaw) ? custRaw[0] : custRaw;
                const customerName =
                  typeof cust?.name === "string" && cust.name.trim() ? cust.name.trim() : undefined;
                return {
                  id: jobRow.id,
                  jobNumber: jobRow.job_number,
                  customerName,
                  installationAddress: jobRow.installation_address,
                  installationApartment: jobRow.installation_apartment,
                  installationFloor: jobRow.installation_floor,
                };
              })()
            : undefined,
        };
      }) as (WorkOrder & {
        job?: {
          id: string;
          jobNumber: string;
          customerName?: string;
          installationAddress?: string;
          installationApartment?: string | null;
          installationFloor?: string | null;
        };
      })[];
    },
  });

  useEffect(() => {
    const channelName = `work-orders-live:${jobId ?? "all"}:${user?.teamId ?? "any"}:${user?.id ?? "anon"}:${realtimeInstanceIdRef.current}`;
    const scopedToFieldTeam = !!(user && isFieldExecutionRole(user.role) && user.teamId);
    const filter = jobId
      ? `job_id=eq.${jobId}`
      : scopedToFieldTeam
        ? `team_id=eq.${user!.teamId}`
        : undefined;

    const channel = supabase.channel(channelName).on(
      "postgres_changes",
      {
        event: "*",
        schema: "public",
        table: "work_orders",
        ...(filter ? { filter } : {}),
      },
      (payload) => {
        const row =
          (payload as { new?: Record<string, unknown> }).new ??
          (payload as { old?: Record<string, unknown> }).old;
        const jid = typeof row?.job_id === "string" ? row.job_id : undefined;
        const oid = typeof row?.id === "string" ? row.id : undefined;
        const status = typeof row?.status === "string" ? (row.status as WorkOrder["status"]) : undefined;
        if (oid && status) {
          patchWorkOrderInAllCaches(queryClient, oid, { status });
        }
        invalidateWorkOrderQueries(queryClient, jid);
        void queryClient.invalidateQueries({ queryKey: ["jobs"], refetchType: "active" });
        void queryClient.invalidateQueries({ queryKey: DASHBOARD_ACCEPTED_MEASUREMENT_FROM_JOBS_QUERY_KEY });
        void queryClient.invalidateQueries({ queryKey: DASHBOARD_WORK_ORDERS_MISSING_TEAM_QUERY_KEY });
        void queryClient.invalidateQueries({ queryKey: ["sales-dashboard-alerts"] });
        void queryClient.invalidateQueries({ queryKey: ["urgent-site-missing-notifications"] });
      },
    ).subscribe();

    return () => {
      void supabase.removeChannel(channel);
    };
  }, [jobId, queryClient, user?.id, user?.role, user?.teamId]);

  const createWorkOrder = useMutation({
    mutationFn: async (newOrder: WorkOrderCreateInput) => {
      if (!newOrder.jobId) {
        throw new Error("Posao je obavezan za radni nalog.");
      }
      if (!newOrder.assignedTeamId) {
        throw new Error("Tim je obavezan za radni nalog.");
      }
      const { checklistItems, ...woFields } = newOrder;
      const { data, error } = await supabase
        .from("work_orders")
        .insert([{
          job_id: woFields.jobId,
          type: woFields.type,
          description: woFields.description,
          measurement_location: woFields.measurementLocation ?? null,
          measurement_scope: woFields.measurementScope ?? null,
          team_id: woFields.assignedTeamId,
          date: workOrderScheduledDatetimeForDb(woFields.date) ?? woFields.date,
          status: woFields.status,
          file_id: woFields.attachmentFileId ?? null,
        }])
        .select()
        .single();

      if (error) throw error;
      const checklistRows =
        checklistItems?.map((d) => d.trim()).filter((d) => d.length > 0) ?? [];
      if (checklistRows.length > 0) {
        const { error: itemsErr } = await supabase.from("work_order_items").insert(
          checklistRows.map((description) => ({
            work_order_id: data.id,
            description,
            is_completed: false,
            measurements: "",
          })),
        );
        if (itemsErr) throw itemsErr;
      }
      await upsertSystemActivity({
        jobId: newOrder.jobId,
        description: `Kreiran radni nalog: ${labelWorkOrderType(newOrder.type)}`,
        systemKey: `work-order-created:${data.id}`,
        authorId: user?.id ?? null,
      });
      await runStatusAutomation(woFields.jobId);
      return data;
    },
    onSuccess: (_data, variables) => {
      invalidateWorkOrderQueries(queryClient, variables.jobId);
      void queryClient.invalidateQueries({ queryKey: ["jobs"], refetchType: "active" });
      void queryClient.invalidateQueries({ queryKey: DASHBOARD_ACCEPTED_MEASUREMENT_FROM_JOBS_QUERY_KEY });
      void queryClient.invalidateQueries({ queryKey: DASHBOARD_WORK_ORDERS_MISSING_TEAM_QUERY_KEY });
      void queryClient.invalidateQueries({ queryKey: ["sales-dashboard-alerts"] });
      void queryClient.invalidateQueries({ queryKey: ["urgent-site-missing-notifications"] });
      toast({ title: "Radni nalog kreiran", description: "Novi radni nalog je uspešno dodat." });
    },
    onError: (error) => {
      toast({ title: "Greška", description: error.message, variant: "destructive" });
    },
  });

  const updateWorkOrder = useMutation({
    onMutate: async (order) => {
      await queryClient.cancelQueries({ queryKey: ["work-orders"] });
      await queryClient.cancelQueries({ queryKey: ["field-team-work-orders"] });
      const snapshots = queryClient.getQueriesData<WorkOrder[]>({ queryKey: ["work-orders"] });
      const fieldSnapshots = queryClient.getQueriesData<WorkOrder[]>({ queryKey: ["field-team-work-orders"] });
      const startedAt =
        order.status === "in_progress" ? new Date().toISOString() : order.fieldStartedAt;
      patchWorkOrderInAllCaches(queryClient, order.id, {
        status: order.status,
        ...(startedAt ? { fieldStartedAt: startedAt } : {}),
      });
      return { snapshots, fieldSnapshots };
    },
    onError: (error, _order, context) => {
      context?.snapshots?.forEach(([key, data]) => queryClient.setQueryData(key, data));
      context?.fieldSnapshots?.forEach(([key, data]) => queryClient.setQueryData(key, data));
      toast({ title: "Greška", description: error.message, variant: "destructive" });
    },
    onSettled: (_data, _error, order) => {
      invalidateWorkOrderQueries(queryClient, order.jobId);
      void queryClient.invalidateQueries({ queryKey: ["jobs"], refetchType: "active" });
      void queryClient.invalidateQueries({ queryKey: DASHBOARD_ACCEPTED_MEASUREMENT_FROM_JOBS_QUERY_KEY });
      void queryClient.invalidateQueries({ queryKey: DASHBOARD_WORK_ORDERS_MISSING_TEAM_QUERY_KEY });
      void queryClient.invalidateQueries({ queryKey: ["sales-dashboard-alerts"] });
      void queryClient.invalidateQueries({ queryKey: ["urgent-site-missing-notifications"] });
    },
    mutationFn: async (order: WorkOrder) => {
      const prev = await supabase.from("work_orders").select("*").eq("id", order.id).single();
      if (prev.error) throw prev.error;
      const prevRow = (prev.data ?? null) as Record<string, unknown> | null;
      const previousStatus = typeof prevRow?.status === "string" ? prevRow.status : undefined;
      const isAutoOrder = isAutoGeneratedWorkOrder(prevRow);

      // Proizvodnja: zatvaranje samo posle svih skeniranih stavki i unetog proizvodnog (terenskog) izveštaja.
      if (order.type === "production" && order.status === "completed") {
        const { data: pendingItems, error: itemsErr } = await supabase
          .from("job_items")
          .select("id")
          .eq("job_id", order.jobId)
          .eq("is_completed", false)
          .limit(1);
        if (itemsErr) throw itemsErr;
        if ((pendingItems ?? []).length > 0) {
          throw new Error("Proizvodni nalog ne može biti završen dok svi bar kodovi ne budu skenirani.");
        }
        const { data: reportRows, error: reportErr } = await supabase
          .from("field_reports")
          .select("id")
          .eq("work_order_id", order.id)
          .limit(1);
        if (reportErr) throw reportErr;
        if (!reportRows?.length) {
          throw new Error("Proizvodni nalog se završava u izveštaju proizvodnje: popunite i sačuvajte proizvodni izveštaj.");
        }
      }

      const transitioningToInProgress =
        order.status === "in_progress" && previousStatus === "pending";
      const transitioningToCompleted =
        order.status === "completed" && previousStatus !== undefined && previousStatus !== "completed";

      /**
       * Montaža / teren / proizvodnja: trigger `prevent_field_team_work_order_content_update` zabranjuje
       * izmenu job_id, type, description, date, team_id, file_id, created_at ako se bilo šta razlikuje od baze
       * (npr. format datuma u klijentu). Za timske uloge uvek šaljemo samo status + terenska vremena.
       */
      if (isFieldExecutionRole(user?.role)) {
        const patch: Record<string, unknown> = { status: order.status };
        if (transitioningToInProgress) patch.field_started_at = new Date().toISOString();
        if (transitioningToCompleted) patch.field_completed_at = new Date().toISOString();
        const { error } = await supabase.from("work_orders").update(patch).eq("id", order.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from("work_orders")
          .update({
            type: order.type,
            description: order.description,
            measurement_location: order.measurementLocation ?? null,
            measurement_scope: order.measurementScope ?? null,
            team_id: order.assignedTeamId ?? null,
            date: workOrderScheduledDatetimeForDb(order.date) ?? order.date,
            status: order.status,
            file_id: order.attachmentFileId ?? null,
            ...(transitioningToInProgress ? { field_started_at: new Date().toISOString() } : {}),
            ...(transitioningToCompleted ? { field_completed_at: new Date().toISOString() } : {}),
          })
          .eq("id", order.id);

        if (error) throw error;
      }
      if (previousStatus && previousStatus !== order.status) {
        await upsertSystemActivity({
          jobId: order.jobId,
          description: `Status radnog naloga: ${labelWorkOrderStatus(previousStatus as WorkOrder["status"])} → ${labelWorkOrderStatus(order.status)}`,
          systemKey: `work-order-status:${order.id}:${previousStatus}:${order.status}`,
          authorId: user?.id ?? null,
        });
      }

      if (order.status === "canceled" && previousStatus !== "canceled" && isAutoOrder) {
        const { data: jobRow, error: jobErr } = await supabase
          .from("jobs")
          .select("status")
          .eq("id", order.jobId)
          .single();
        if (jobErr) throw jobErr;

        const explicitPrevStatus =
          typeof prevRow?.auto_prev_job_status === "string"
            ? (prevRow.auto_prev_job_status as JobStatus)
            : null;
        const inferredPrevStatus =
          explicitPrevStatus ||
          (typeof jobRow?.status === "string"
            ? await resolvePreviousJobStatusFromActivities(order.jobId, jobRow.status)
            : null);

        if (inferredPrevStatus && inferredPrevStatus !== jobRow.status) {
          const { error: restoreErr } = await supabase
            .from("jobs")
            .update({ status: inferredPrevStatus })
            .eq("id", order.jobId);
          if (restoreErr) throw restoreErr;

          await upsertSystemActivity({
            jobId: order.jobId,
            description: `Automatski nalog otkazan ručno: status posla vraćen ${labelJobStatus(jobRow.status as JobStatus)} → ${labelJobStatus(inferredPrevStatus)}`,
            systemKey: `auto-wo-cancel-restore-status:${order.id}:${jobRow.status}:${inferredPrevStatus}`,
            authorId: user?.id ?? null,
          });
        }
        return;
      }

      await runStatusAutomation(order.jobId);
    },
    onSuccess: () => {
      toast({ title: "Radni nalog ažuriran", description: "Promene su uspešno sačuvane." });
    },
  });

  return {
    workOrders,
    isLoading,
    isError,
    error,
    createWorkOrder,
    updateWorkOrder,
  };
}
